### ISSUE TITLE
Update Generic dialect

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/generic-virtual-schema#3]
## Problem

Generic dialect needs to be updated with the latest vs-common-jdbc dependency.

**Comment by redcatbear** [comment]
@AnastasiiaSergienko: please add a description and split documentation and feature parts.

**Comment by redcatbear** [comment]
@AnastasiiaSergienko, please add detailed description and split into two separate tickets, one for the feature, one for the documentation.
