### ISSUE TITLE
Generic VS fails with Informix

### ISSUE THREAD

**Issue by acrey1** [exasol/generic-virtual-schema#4]
Steps below:

1. Connection set up (redacted)
2. Verification of connection setup and pushdown query via import
3. Creation of container schema
4. Creation of adapter script in container schema
5. Creation of virtual schema against adapter (fail)

CREATE OR REPLACE CONNECTION INFORMIX
      TO 'jdbc:informix-sqli://hostname:9088/dbname:INFORMIXSERVER=pronto_net'
      USER 'username'
      IDENTIFIED BY 'password';
 
IMPORT
FROM JDBC AT INFORMIX STATEMENT
'SELECT tabid, tabname, owner, nrows
FROM systables
WHERE owner = ''informix'' AND nrows > 1000
ORDER BY tabid';
 
tabid|tabname       |owner                           |nrows  |
-----|--------------|--------------------------------|-------|
    1|systables     |informix                        | 4062.0|
    2|syscolumns    |informix                        |86164.0|
    3|sysindices    |informix                        | 6088.0|
    4|systabauth    |informix                        | 2062.0|
    6|sysviews      |informix                        | 7101.0|
    8|sysdepend     |informix                        | 1992.0|
   11|sysconstraints|informix                        | 1990.0|
   15|syscoldepend  |informix                        | 1990.0|
   17|sysprocbody   |informix                        | 3768.0|
   24|sysdistrib    |informix                        | 8138.0|
   25|sysfragments  |informix                        | 5976.0|
   26|sysobjstate   |informix                        | 7966.0|
   60|sysproccolumns|informix                        | 1726.0|
 
 
CREATE SCHEMA IFXTEST;
 
CREATE OR REPLACE JAVA ADAPTER SCRIPT IFXTEST.JAVA_ADAPTER AS
         %scriptclass com.exasol.adapter.RequestDispatcher;
         %jar /buckets/bucketfs1/drivers/virtual-schema-dist-8.0.0-generic-1.0.0.jar;
         %jar /buckets/bucketfs1/drivers/ifxjdbc.jar;
/
 
CREATE VIRTUAL SCHEMA VS_IFXTEST
         USING IFXTEST.JAVA_ADAPTER
         WITH
         SQL_DIALECT = 'GENERIC'
         SCHEMA_NAME = 'pronto'
         CONNECTION_NAME = 'INFORMIX';
 
SQL Error [22002]: VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall 
com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create remote metadata reader for the generic SQL dialect. Caused by: No suitable driver found for jdbc:informix-sqli://hostname:9088/dbname:INFORMIXSERVER=pronto_net
 
 
![2021-01-23 06_58_35-EXAoperation_ cluster1](https://user-images.githubusercontent.com/69837156/105546903-0820c980-5d52-11eb-8fda-945e0a7a38c3.png)
![Buckets](https://user-images.githubusercontent.com/69837156/105547202-5d5cdb00-5d52-11eb-9567-535f172a07cb.png)

**Comment by redcatbear** [comment]
Hi @acrey1. This sounds familiar:
https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/faq.md#sqlexception-no-suitable-driver-found

In all previous cases the driver was lacking the service description file internally. Please check the driver as described in the link above.

**Comment by acrey1** [comment]
There are *two* versions of IBM’s ifxjdbc.jar.  It appears that the version that comes with the SDK does not contain META-INF/services, the packaged separately-downloadable JDBC driver does.  The first one works for a CONNECTION-based JDBC query only; the second one works for a Java adapter script also for a Virtual Schema.
